add cleanup trap

diff --git a/sendanywhere.SlackBuild b/sendanywhere.SlackBuild
--- a/sendanywhere.SlackBuild
+++ b/sendanywhere.SlackBuild
@@ -50,30 +50,48 @@ RELEASE=${RELEASE:-latest}    # stable, beta, or unstable
 SOURCE="$SRCDIR/${PRGNAM}_${RELEASE}_${DEBARCH}.deb"
 SRCURL="https://update.send-anywhere.com/linux_downloads/${PRGNAM}_${RELEASE}_${DEBARCH}.deb"
 
-# Source file availability:
-if ! [ -f ${SOURCE} ]; then
-  echo "Source '$(basename ${SOURCE})' not available yet..."
-  # Check if the $SRCDIR is writable at all - if not, download to $OUTPUT
-  [ -w "$SRCDIR" ] || SOURCE="$OUTPUT/$(basename $SOURCE)"
-  if [ -f ${SOURCE} ]; then echo "Ah, found it!"; continue; fi
-  if ! [ "x${SRCURL}" == "x" ]; then
-    echo "Will download file to $(dirname $SOURCE)"
-    wget -nv -T 20 -O "${SOURCE}" "${SRCURL}" || true
-    if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
-      echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
-      mv -f "${SOURCE}" "${SOURCE}".FAIL
+download() {
+  local SOURCE="$1"
+  local SRCURL="$2"
+  local SRCDIR="$3"
+  local OUTPUT="$4"
+
+  # Source file availability:
+  if ! [ -f ${SOURCE} ]; then
+    echo "Source '$(basename ${SOURCE})' not available yet..."
+    # Check if the $SRCDIR is writable at all - if not, download to $OUTPUT
+    [ -w "$SRCDIR" ] || SOURCE="$OUTPUT/$(basename $SOURCE)"
+    if [ -f ${SOURCE} ]; then echo "Ah, found it!"; continue; fi
+    if ! [ "x${SRCURL}" == "x" ]; then
+      echo "Will download file to $(dirname $SOURCE)"
+      wget -nv -T 20 -O "${SOURCE}" "${SRCURL}" || true
+      if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+        echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+        mv -f "${SOURCE}" "${SOURCE}".FAIL
+        exit 1
+      fi
+    else
+      echo "File '$(basename ${SOURCE})' not available... aborting the build."
       exit 1
     fi
-  else
-    echo "File '$(basename ${SOURCE})' not available... aborting the build."
-    exit 1
   fi
-fi
 
-if [ "$P1" == "--download" ]; then
-  echo "Download complete."
+  if [ "$P1" == "--download" ]; then
+    echo "Download complete."
+    exit 0
+  fi
+}
+
+download $SOURCE $SRCURL $SRCDIR $OUTPUT
+
+cleanup() {
+  echo
+  echo "Cleaning up..."
+  [ -f ${CWD}/${PKGNAM}-${RELEASE}_current_${DEBARCH}.deb ] && \
+    rm -fv ${CWD}/${PKGNAM}-${RELEASE}_current_${DEBARCH}.deb
   exit 0
-fi
+}
+trap cleanup SIGINT SIGQUIT SIGABRT
 
 # Get the version from the Debian/Ubuntu .deb (thanks to Fred Richards):
 SRCVER=$(ar p ${PRGNAM}_${RELEASE}_${DEBARCH}.deb control.tar.gz 2> /dev/null | tar zxO control 2> /dev/null | grep Version | awk '{print $2}')
@@ -92,6 +110,8 @@ SRCVER=$(ar p ${PRGNAM}_${RELEASE}_${DEBARCH}.deb control.tar.gz 2> /dev/null | 
 
 set -e
 printf "Building Send Anywhere, version %s\n" $SRCVER
+echo "Press any key to continue or Ctrl-C to abort..."
+read
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -128,7 +148,9 @@ rm -rf $PKG/usr/share/doc
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
-zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
+zcat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
+
+cleanup
